apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: python-tools
build:
  artifacts:
  - image: us-central1-docker.pkg.dev/genuine-flight-317411/devel/python-tools
    docker:
      dockerfile: Dockerfile
  local:
    push: true
    concurrency: 0
deploy:
  kubectl:
    manifests:
    - test.yaml


profiles:
- name: apple-m1-dev
  build:
    artifacts:
      - image: us-central1-docker.pkg.dev/genuine-flight-317411/devel/python-tools
        context: .
        custom:
          buildCommand: ./build_on_apple_m1.sh
    local:
      push: true
      concurrency: 0
