apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-tools
  labels:
    app: python-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-tools
  template:
    metadata:
      labels:
        app: python-tools
    spec:
      hostPID: true
      containers:
        - name: python-tools
          image: us-central1-docker.pkg.dev/genuine-flight-317411/devel/debug-toolkit
          imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_PTRACE
